<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hermes.FileModule\Hermes.FileModule.csproj" />
    <ProjectReference Include="..\Hermes.LoggerModule\Hermes.LoggerModule.csproj" />
    <ProjectReference Include="..\Hermes.MailModule\Hermes.MailModule.csproj" />
  </ItemGroup>

</Project>
